---
# configure base dependencies for nest

- name: make sure node ppa is available
  apt_repository: repo='ppa:chris-lea/node.js'

- name: update apt-cache if needed
  apt: update_cache=yes

- name: make sure nodejs is installed
  apt: name=nodejs state=present


- name: make sure nginx is installed
  apt: name=nginx state=present
